### ISSUE TITLE
[Feature] Support + as space in search

### ISSUE THREAD

**Issue by kmodexc** [TUM-Dev/navigatum#95] opened 2022-05-04 17:23 UTC
Many [libraries](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URLEncoder.html) use + in the query string to encode space. It would be nice if `nav.tum.sexy/search/` could support that too.

**Comment by CommanderStorm** [comment] 2022-05-04 20:30
Please notice, that there seems to be a difference in what is allowed in path and querry parameters. we use a path parameter.
see https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20 :
> For HTTP URLs, a space in a path fragment part has to be encoded to "%20" (not, absolutely not "+"), while the "+" character in the path fragment part can be left unencoded

If changing our api is better for implementation, we could eazily change this design-decision.

**Comment by CommanderStorm** [comment] 2022-05-04 21:34
While #79 is not yet reviewed+in main, you can look at https://editor.swagger.io/?url=https://raw.githubusercontent.com/TUM-Dev/navigatum/openapi/openapi.yaml for a better documentation.

Once the PR is merged, a more recent version will be availible at https://editor.swagger.io/?url=https://raw.githubusercontent.com/TUM-Dev/main/openapi/openapi.yaml

**Comment by CommanderStorm** [comment] 2022-05-04 21:53
I am going to close this issue, as everything is working as intended. 

We can reopen if you require this being a querry parameter, or can reason, that this would be better API-design. I have found blogs for both sides of the argument.
Pro-path is mainly that it is a required parameter this way..
Pro-querry is mainly that they are kind of "filtering the result of a query", even if the query is select all.

**Closed by CommanderStorm** 2022-05-04 21:53 UTC
Labels: feature

**Comment by CommanderStorm** [comment] 2022-05-05 16:53
changed to a query parameter in #96
