### ISSUE TITLE
[Bug] Siteplan FMI instead of MW 

### ISSUE THREAD

**Issue by N0W0RK** [TUM-Dev/NavigaTUM#874] opened 2023-11-09 10:30 UTC
**Describe the bug**
Looking at some rooms in the MW(5500) the FMI Siteplan is shown.

**To Reproduce**
* Go to https://nav.tum.de/room/5505.02.550
Check Site Plans

**Expected behavior**
Either the MW Siteplan should be shown or no sitplan as the MW Plans don't seem to be available.

**Screenshots**
![image](https://github.com/TUM-Dev/NavigaTUM/assets/22464684/0abb8618-6afa-4202-9caf-bb2c439a6b19)

**Desktop (please complete the following information):**

- OS: 6.1.53-1-MANJARO
- Browser: Firefox
- Version: 117.0.1

**Comment by CommanderStorm** [comment] 2023-11-11 17:54
Duplicate of https://github.com/TUM-Dev/NavigaTUM/issues/512

TLDR: I have made some refactoring attempts to make this bug in the map-assignemnt code more obvious, but have not found the edgecase which allows these bad-asignments

**Closed by CommanderStorm** 2023-11-11 17:54 UTC
Labels: bug
