### ISSUE TITLE
[Bug] Site crashes when changing theme/language on the `/api` page

### ISSUE THREAD

**Issue by Guyonsteroids** [TUM-Dev/NavigaTUM#1006] opened 2024-03-04 19:54 UTC
**Describe the bug**
The website crashes and is unreachable when the theme or language is changed on the https://nav.tum.de/api page.

**To Reproduce**
1. Navigate to https://nav.tum.de/api
2. Scroll down and change theme. 
3. ERR_ADDRESS_UNREACHABLE / ERR_CONNECTION_REFUSED

**Expected behavior**
Not crash and correctly change themes

**Screenshots**
-

**Desktop (please complete the following information):**

OS: MacOS
Browser: Opera GX
Build Info:
LVL5 (core: 107.0.5045.37) (arm64)
System:macOS Version 14.3.1 (Build 23D60) 14.3.1 arm64
Chromium version:121.0.6167.160

**Smartphone (please complete the following information):**

N/A

**Additional context**
The site works fine if the theme/language is changed on any other page and then the API page is requested.

**Comment by CommanderStorm** [comment] 2024-03-04 21:49
The site does not quite crash.
The issue is that `/api` is not correctly routed and thus only reachable externally.
https://github.com/TUM-Dev/NavigaTUM/blob/7d218be242a235cfd872ccdcbc5ecc148814693b/webclient/nginx.conf#L67-L69

is to blame, but I have not had the time to figure out how to convince nginx to route `/api` via the normal route:
https://github.com/TUM-Dev/NavigaTUM/blob/7d218be242a235cfd872ccdcbc5ecc148814693b/webclient/nginx.conf#L80-L87

**Comment by CommanderStorm** [comment] 2024-03-05 14:32
Resolved by https://github.com/TUM-Dev/NavigaTUM/commit/d0c7b97ab208071506816c739599590fdee17353

**Closed by CommanderStorm** 2024-03-05 14:32 UTC
Labels: bug
